const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s); let incidents=[], cameras=[], watchData=[];
function api(path,opts={}){return fetch(path,{...opts,headers:{...(opts.body instanceof FormData?{}:{'Content-Type':'application/json'}),...(opts.headers||{})}}).then(async r=>{let x;try{x=await r.json()}catch{ x=null }if(r.status===401){location.href='/login';throw Error('Session expired')}if(!r.ok)throw Error(x?.detail||'Request failed');return x})}
function showPage(p){$$('.page').forEach(x=>x.classList.remove('active'));$('#'+p).classList.add('active');$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===p));if(p==='incidents')loadIncidents();if(p==='watchlist')loadWatchlist();if(p==='cameras')loadCameras()}
$$('.nav').forEach(x=>x.onclick=()=>showPage(x.dataset.page));
function clock(){let d=new Date();$('#clock').textContent=d.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'})}setInterval(clock,1000);clock();
async function boot(){try{let u=await api('/api/me');$('#userLabel').textContent=u.username;$('#securityUser').textContent=u.username;await Promise.all([loadIncidents(),loadStats(),loadCameras(),loadDemos(),loadWatchlist()])}catch(e){console.error(e)}}
async function loadStats(){try{let x=await api('/api/stats');$('#eventsCount').textContent=x.events_today;$('#highCount').textContent=x.high_risk;$('#openCount').textContent=x.open;$('#badge').textContent=x.open;let t=Math.max(1,x.events_today);[['Normal',x.normal],['Medium',x.medium],['High',x.high],['Critical',x.critical_count]].forEach(([n,v])=>{$('#bar'+n).style.width=(v/t*100)+'%';$('#pct'+n).textContent=Math.round(v/t*100)+'%'})}catch(e){}}
async function loadIncidents(){try{incidents=await api('/api/incidents');$('#eventsCount').textContent=incidents.length;$('#highCount').textContent=incidents.filter(x=>x.risk>=65).length;$('#openCount').textContent=incidents.filter(x=>x.status!=='SOLVED').length;$('#badge').textContent=incidents.filter(x=>x.status!=='SOLVED').length;$('#recent').innerHTML=incidents.slice(0,6).map(x=>`<div class="alert" onclick="openIncident(${x.id})"><div><b>${esc(x.event_type)}</b><small>${esc(x.video_name)} • ${x.created_at.replace('T',' ')}</small></div><div class="risk ${x.severity.toLowerCase()}">${x.risk}/100</div></div>`).join('')||'<p class="muted">No incidents yet. Analyze a demo feed to generate one.</p>';$('#incidentTable').innerHTML=incidents.map(x=>`<tr><td>${x.created_at.replace('T',' ')}</td><td><b>${esc(x.event_type)}</b><small>${esc(x.video_name)}</small></td><td><span class="risk ${x.severity.toLowerCase()}">${x.risk}</span><div class="tinybar"><i style="width:${x.risk}%"></i></div></td><td>${x.confidence}%</td><td>${x.persons}</td><td><span class="badge ${x.status==='SOLVED'?'green':x.status==='ACKNOWLEDGED'?'amber':''}">${x.status}</span></td><td><button class="ghost mini" onclick="event.stopPropagation();openIncident(${x.id})">VIEW</button> ${x.status==='NEW'?`<button class="ghost mini" onclick="event.stopPropagation();ack(${x.id})">ACK</button>`:''} ${x.status==='ACKNOWLEDGED'?`<button class="ghost mini solvebtn" onclick="event.stopPropagation();solve(${x.id})">SOLVED</button>`:''} ${x.status==='SOLVED'?`<button class="ghost mini deletebtn" onclick="event.stopPropagation();removeIncident(${x.id})">REMOVE</button>`:''}</td></tr>`).join('')}catch(e){}}
async function ack(id){try{await api('/api/incidents/'+id+'/ack',{method:'POST'});toast('Incident acknowledged');await loadIncidents();loadStats()}catch(e){toast(e.message)}}
async function solve(id){try{await api('/api/incidents/'+id+'/solve',{method:'POST'});toast('Incident marked solved');closeModal();await loadIncidents();loadStats()}catch(e){toast(e.message)}}
async function removeIncident(id){if(!confirm('Remove this SOLVED incident and its evidence snapshot? This cannot be undone.'))return;try{await api('/api/incidents/'+id,{method:'DELETE'});toast('Solved incident and evidence removed');await loadIncidents();loadStats()}catch(e){toast(e.message)}}
function openIncident(id){let x=incidents.find(a=>a.id===id);if(!x)return;let actions='';if(x.status==='NEW')actions=`<button class="primary" onclick="ack(${x.id});closeModal()">Acknowledge Alert</button>`;else if(x.status==='ACKNOWLEDGED')actions=`<button class="primary" onclick="solve(${x.id})">Mark Incident Solved</button>`;else actions=`<button class="ghost deletebtn" onclick="removeIncident(${x.id});closeModal()">Remove Solved Incident</button>`;$('#modalContent').innerHTML=`<p class="eyebrow">INCIDENT #${x.id} • ${x.status}</p><h2>${esc(x.event_type)}</h2><div class="meta"><div>RISK<strong class="risk ${x.severity.toLowerCase()}">${x.risk}/100</strong></div><div>CONFIDENCE<strong>${x.confidence}%</strong></div><div>PERSONS<strong>${x.persons}</strong></div><div>DURATION<strong>${x.duration}s</strong></div></div><img class="evidence" src="/evidence/${x.evidence}"><h3>Risk factors</h3><div class="factors">${x.factors.map(f=>`<span>✓ ${esc(f)}</span>`).join('')}</div><div class="modalactions"><a class="ghost linkbtn" href="/evidence/${x.evidence}" target="_blank">Open Evidence</a>${actions}</div>`;$('#detailModal').classList.add('show')}
function closeModal(){$('#detailModal').classList.remove('show')}$('#detailModal').onclick=e=>{if(e.target.id==='detailModal')closeModal()};
async function loadDemos(){try{let ds=await api('/api/demo-videos');$('#demos').innerHTML=ds.map(d=>`<div class="demo"><video src="${d.url}" muted loop autoplay playsinline></video><div style="flex:1"><b>${pretty(d.name)}</b><small>${scenario(d.name)}</small><div><button class="ghost mini" onclick="selectDemo('${d.url}','${d.name}')">Use this feed</button><button class="ghost mini" onclick="previewLive('${d.url}','${pretty(d.name)}')">Live preview</button></div></div></div>`).join('')}catch(e){}}
function pretty(n){return n.replace('.mp4','').replaceAll('_',' ')}function scenario(n){if(n.includes('Normal'))return 'Baseline • normal patrol';if(n.includes('Fence'))return 'Critical • virtual-fence intrusion';if(n.includes('Multiple'))return 'High • multiple-person approach';return 'High • loitering near fence'}
function selectDemo(url,name){fetch(url).then(r=>r.blob()).then(b=>setFile(new File([b],name,{type:'video/mp4'})))}function setFile(f){window.currentFile=f;$('#selected').classList.remove('hidden');$('#selected').innerHTML=`<b>Selected:</b> ${esc(f.name)} <span>• ${(f.size/1024/1024).toFixed(2)} MB</span>`;$('#analyzeBtn').classList.remove('hidden')}
$('#file').onchange=e=>e.target.files[0]&&setFile(e.target.files[0]);
$('#analyzeBtn').onclick=async()=>{if(!window.currentFile)return;$('#progress').classList.remove('hidden');$('#analyzeBtn').disabled=true;$('#progressText').textContent='Scanning video → detecting movement → evaluating zone rules…';let fd=new FormData();fd.append('file',window.currentFile);try{let x=await api('/api/analyze',{method:'POST',body:fd});renderResult(x);loadIncidents();loadStats()}catch(e){toast(e.message)}finally{$('#progress').classList.add('hidden');$('#analyzeBtn').disabled=false}};
function renderResult(x){let cls=x.severity.toLowerCase();$('#result').classList.remove('hidden');$('#result').innerHTML=`<div class="panelhead"><div><p class="eyebrow">ANALYSIS COMPLETE • INCIDENT #${x.id}</p><h3>${esc(x.event_type)}</h3></div><span class="badge ${cls==='low'?'green':''}">${x.severity}</span></div><div class="resultgrid"><div><img class="evidence" src="/evidence/${x.evidence}"><div class="caption">Evidence snapshot • restricted-zone overlay</div></div><div><div class="score risk ${cls}">${x.risk}<span>/100 RISK</span></div><div class="meter"><i style="width:${x.risk}%"></i></div><div class="resultstats"><span>Confidence <b>${x.confidence}%</b></span><span>People <b>${x.persons}</b></span><span>Duration <b>${x.duration}s</b></span></div><h4>Why was this flagged?</h4><div class="factors">${x.factors.map(f=>`<span>✓ ${esc(f)}</span>`).join('')}</div><button class="primary" onclick="showPage('incidents')">Open Incident Log →</button></div></div>`;$('#result').scrollIntoView({behavior:'smooth'})}
async function loadCameras(){try{if(!cameras.length)cameras=await api('/api/cameras');$('#camCount').textContent=cameras.length;$('#onlineCams').textContent=cameras.filter(c=>c.status==='ONLINE').length+'/'+cameras.length;$('#cameraGrid').innerHTML=cameras.map(c=>`<div class="camera"><div class="feed"><video src="/demo/${c.demo}" autoplay muted loop playsinline></video><span class="rec">● LIVE</span><span class="signal">▮▮▮ ${c.signal}</span><span class="camtag">${c.id} • ${c.name}</span><div class="zone"><b>RESTRICTED</b></div><div class="personbox"><span>PERSON • AI</span></div><div class="feedfooter"><span>● ${c.fps} FPS</span><span>AI TRACKING</span></div></div><div class="caminfo"><div><b>${c.name}</b><small>${c.zone} • ${c.objects} objects</small></div><span class="status ${c.status==='ALERT'?'alertstatus':''}">● ${c.status}</span></div><div class="cameraevent"><span>EVENT</span><b>${esc(c.event)}</b></div><div class="camactions"><button class="ghost widecam" onclick="useCamera('${c.demo}','${c.id}')">Analyze</button><button class="ghost mini" onclick="previewLive('/demo/${c.demo}','${c.id} • ${c.name}')">LIVE</button></div></div>`).join('')}catch(e){}}
function useCamera(d,id){showPage('analyze');selectDemo('/demo/'+d,d);toast(id+' feed loaded')}
function previewLive(url,title){$('#liveContent').innerHTML=`<p class="eyebrow">LIVE CCTV CHANNEL</p><h2>${esc(title)}</h2><div class="biglive"><video src="${url}" autoplay muted loop controls playsinline></video><div class="liveoverlay"><span>● LIVE</span><span>AI MONITORING</span><span>LOCAL FEED</span></div></div><div class="liveinfo"><span>🔒 Authenticated feed</span><span>24–26 FPS</span><span>Encrypted local session</span></div>`;$('#liveModal').classList.add('show')}
function closeLive(){$('#liveModal').classList.remove('show');$('#liveContent').innerHTML=''}$('#liveModal').onclick=e=>{if(e.target.id==='liveModal')closeLive()};
async function loadWatchlist(){try{watchData=await api('/api/watchlist');$('#watchTotal').textContent=watchData.length;$('#watchHigh').textContent=watchData.filter(x=>x.priority==='HIGH').length;$('#watchHits').textContent=watchData.reduce((a,x)=>a+(x.hit_count||0),0);filterWatch()}catch(e){}}
function filterWatch(){if(!watchData.length){$('#watchGrid').innerHTML='<div class="panel"><p class="muted">No watchlist entries.</p></div>';return}let q=($('#watchSearch')?.value||'').toLowerCase();let f=$('#watchFilter')?.value||'ALL';let ds=watchData.filter(x=>(f==='ALL'||x.priority===f)&&[x.plate,x.vehicle,x.note].join(' ').toLowerCase().includes(q));$('#watchGrid').innerHTML=ds.map(x=>`<div class="platecard"><div class="platehead"><div class="plate">${esc(x.plate)}</div><span class="priority ${x.priority.toLowerCase()}">● ${esc(x.priority)}</span></div><p>${esc(x.vehicle)}</p><small>${esc(x.note)}</small><div class="platefacts"><span>HITS <b>${x.hit_count||0}</b></span><span>LAST SEEN <b>${esc(x.last_seen||'-')}</b></span><span>EXPIRES <b>${esc(x.expires_at||'No expiry')}</b></span></div><div class="plateactions"><button class="ghost mini matchbtn" onclick="matchPlate(${x.id})">✓ Simulate Match</button><button class="ghost mini deletebtn" onclick="deletePlate(${x.id})">Remove</button></div></div>`).join('')||'<div class="panel"><p class="muted">No matching plates.</p></div>'}
async function addPlate(){let p=prompt('Plate number (example: TS09AB1234):');if(!p)return;let priority=prompt('Priority: HIGH / MONITOR / LOW','MONITOR')||'MONITOR';let vehicle=prompt('Vehicle type:','Vehicle / Sedan')||'Unknown vehicle';let note=prompt('Operator note:','Added by operator')||'Added by operator';let expires=prompt('Expiry date/time (optional):','')||'';try{await api('/api/watchlist',{method:'POST',body:JSON.stringify({plate:p,priority,vehicle,note,expires_at:expires})});await loadWatchlist();toast('Plate added to watchlist')}catch(e){toast(e.message)}}
async function matchPlate(id){try{let x=await api('/api/watchlist/'+id+'/match',{method:'POST'});toast('ANPR MATCH: '+x.plate+' • '+x.priority);loadWatchlist()}catch(e){toast(e.message)}}
async function deletePlate(id){if(!confirm('Remove this plate from the watchlist?'))return;try{await api('/api/watchlist/'+id,{method:'DELETE'});loadWatchlist();toast('Plate removed')}catch(e){toast(e.message)}}
async function changePassword(){let oldp=prompt('Current password:');if(oldp===null)return;let newp=prompt('New password (10+ chars, upper + lower + number):');if(newp===null)return;let confirmP=prompt('Confirm new password:');if(newp!==confirmP)return toast('Passwords do not match');try{await api('/api/change-password',{method:'POST',body:JSON.stringify({old_password:oldp,new_password:newp})});toast('Password changed successfully. Please sign in again.');setTimeout(logout,800)}catch(e){toast(e.message)}}
async function logout(){try{await fetch('/api/logout',{method:'POST'})}finally{location.href='/login'}}
function toast(t){let x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),2600)}function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
boot();
